### useQueryParam, no default version

###
GET http://localhost:8080/test?version_query_param=1.0.0



###according to docs, should match the mapping with no explicit mapping, but doesn't
GET http://localhost:8080/test?version_query_param=0.0.0



###
GET http://localhost:8080/test?version_query_param=1.1.1



###according to docs, should match version 1.2+, but doesn't
GET http://localhost:8080/test?version_query_param=1.5

###