### useQueryParams, no default version

###explicitly matching mapping 1.0.0
GET http://localhost:8080/test?version_query_param=1.0.0

###explicitly matching mapping 1.1.1
GET http://localhost:8080/test?version_query_param=1.1.1


###according to docs, should match the mapping with no explicit mapping, since the version that doesn't have the explicit matching is passed; but doesn't
GET http://localhost:8080/test?version_query_param=0.0.0


###according to docs, should match version 1.2+, but doesn't
GET http://localhost:8080/test?version_query_param=1.5

###request with no explicit version matches the mapping without versions
GET http://localhost:8080/test


###no-version request for path that has versions: max version is used
GET http://localhost:8080/test/test1

###wildcard for param value: no results
GET http://localhost:8080/test/test1?version_query_param=1.3+

###wildcard for param value, the similar wildcard mapping exists: no results
GET http://localhost:8080/test/test1?version_query_param=3.0+