###
GET http://localhost:8080/requiredVersions
Version-header-required: 1.0.0



###
GET http://localhost:8080/requiredVersions


###
GET http://localhost:8080/requiredVersions/test1



###
GET http://localhost:8080/requiredVersions/test1
Version-Header-Required: 1.5.0


###