### useRequestHeader
# header is highlighted as 'unknown'
###
GET http://localhost:8080/requestHeader
Version-header: 1.2.0



###1.0.0
GET http://localhost:8080/requestHeader



###400 BAD_REQUEST "Invalid API version: '1.0.0'."
GET http://localhost:8080/requestHeader
Version-header: 1.0.0


###1.3+
GET http://localhost:8080/requestHeader
Version-header: 1.3.0



###1.3+
GET http://localhost:8080/requestHeader
Version-header: 1.3



###400 BAD_REQUEST "Invalid API version: '1.5'."
GET http://localhost:8080/requestHeader
Version-header: 1.5



###"Invalid API version: '1.7'."
GET http://localhost:8080/requestHeader/test1
Version-header: 1.7



###"Required header 'Version-header' is not present."
GET http://localhost:8080/requestHeader/test1



###
GET http://localhost:8080/requestHeader/test2
Version-Header: 1.2.0
rh1: foo
rh2: bar